### ISSUE TITLE
can't to secure connection

### ISSUE THREAD

**Issue by amirmehdi** [RooyeKhat-Media/iGap-API#1]
hello,
I tried to send #2 request so much based on you said and source code of igap+ but I never get #30002 response and get 3 times #30001 response and then ignored.
this repo contains my simple code in nodejs language and protojs files. 
https://github.com/amirmehdi/igap
thanks for your help...

**Comment by amereii** [comment]
@amirmehdi see https://github.com/RooyeKhat-Media/iGap-API/blob/master/docs/guide/v1/Transmission.md#format
You have a mistake on sending request to the server


Replace the following lines instead of ```connection.send(ConnectionSymmetricKey);``` 

```js
var requestPayload = protos.proto.ConnectionSymmetricKey.encode(ConnectionSymmetricKey).finish();
var requestActionId = 2;
const actionIdData = new DataView(new ArrayBuffer(2), 0);
actionIdData.setUint16(0, requestActionId, true);

const pack = new Uint8Array(2 + requestPayload.byteLength);
pack.set(new Uint8Array(actionIdData.buffer));
pack.set(requestPayload, 2);

connection.send(new Buffer(pack));
```


We highly recommend you , implement an `invoke` function like iGap-Plus
https://github.com/RooyeKhat-Media/iGap-Plus/blob/master/src/modules/Api/index.js#L104
https://github.com/RooyeKhat-Media/iGap-Plus/tree/master/src/modules/Api
https://github.com/RooyeKhat-Media/iGap-Plus/tree/master/src/modules/Handler

**Comment by amirmehdi** [comment]
oh thanks a lot!
